//Lab 4 - Intro to Loops and Conditionals
//Let's get Mathy!

//const a = 42.78
//const b = 1.1
//const c = -2
//const d = .5
//const e = 16

//Round a down
//console.log(Math.floor(a))
////Round b up
//console.log(Math.ceil(b))
////Find the absolute value of b - a
//console.log(Math.abs(b - a))
////Find the largest number of a, b, c, d, e
//console.log(Math.max(a, b, c, d, e))
////Find the smallest number of a, b, c, d, e
//console.log(Math.min(a, b, c, d, e))
////Find the square root of e
//console.log(Math.sqrt(e))
////Raise e to the power of d
//console.log(Math.pow(e, d))
////Make a digital die 0 generate a random number between 1 - 6
////Generate a random number between 1 and 6
//console.log(Math.ceil(Math.random() * 6))

//Strings Activity 1
let firstVariable = "Hello World";
firstVariable = 4;
let secondVariable = firstVariable
secondVariable = "Goodbye World";
//What is the value of firstVariable?
//Answer: "Goodbye World" *WRONG* Answer: 4
console.log(firstVariable)

//Strings - Combine it
let yourName = "Nicholas";
let expression = "Hello my name is ";
console.log(expression + yourName)

//Booleans Activity
//Using the provided variable definitions, replace the blanks with a mathematical or boolean operator that evaluates the expression to true.
const a = 6;
const b = 100;
const c = -5;
const d = 3000;
const e = 'Jelly Bean';

console.log(e === 'Jelly Bean')
console.log(48 !== '48')
console.log('e' !== 'Eh')

//The Farm
let animal = "cow";
animal = "pig";
if (animal === "cow") {
  console.log("mooo")
} else {
  console.log("Hey! You're not a cow")
}

////Driver's Ed
//const age = x
//if (age >= 16) {
//  console.log("Here are the keys")
//} else {
//  console.log("Sorry, you're too young")
//}

//Just Loop It
//Write code that will print out all the numbers in the range 0 - 10.
for (let i = 0; i <= 10; i++) {
  console.log(i)
}
//Write code that will print out all the numbers in the range 500 - 50.
for (let b = 500; b >= 50; b--) {
  console.log(b)
}

//Let's Get Odd
//Print out the odd numbers that are within the range of 1 - 100.
//Adjust your code to add a message next to the odd number that says: "is an odd number".
for (let n = 1; n <= 100; n++) {
  if (n % 2 === 1) {
    console.log(n + " is an odd number")
  }
}

//Give me Five
//For the numbers 0 - 100, print out "I found a number. High five!" if the number is a multiple of five.
for (let m = 1; m <= 100; m++) {
  if (m % 5 === 0) {
    console.log("I found a ", m, ". High five!")
  }
}

//Euler Problem
//Numbers below 10 that are multiples of 3 or 5 are 3, 5, 6, and 9. The sum of these is 23.
//Find th sum of all the multiples of 3 or 5 below 1000.

//if x % 3 === 0, x % 5 === 0, 

//Savings account
//Write code that will save the sum of all the numbers betweem 1-10 to a variable called bank_account.
//You got a bonus! Your pay is now doubled each week. Write code that will save the sum of all the numbers between 1 - 100 multiplied by 2.

let sum = 0;
for (let z = 0; z <= 10; z++) {
  sum = sum + z
}
let bank_account = sum
console.log(bank_account)

let newSum = 0;
for (let s = 0; s <= 100; s++) {
  newSum = newSum + (s * 2)
}
let newTotal = newSum
console.log(newTotal)

//Create the fibonacci sequence using JavaScript
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//Fibonacci sequence generated by adding the previous two terms. Starting with (1) and (2) the result is (3) then you add (3) and (2) to get (5) and so on.

//Pseudocode: Write the first 10 fibonacci numbers
//Count the numbers from 1-10. For each of those numbers, print the sum of that number and that number and the previous number.